### ISSUE TITLE
project 파일의 ignore 프로퍼티가 제대로 동작하지 않는 이슈

### ISSUE THREAD

**Issue by JunhoeKim** [onetop21/MLAppDeploy#15]
로컬에서 테스트하는동안 다운로드받은 `FashionMNIST/` 를 ignore하기 위하여 아래와 같이 설정하였습니다.
그러나 FashtionMNIST 폴더와 그 안의 데이터들이 여전히 복사되서 이동하는 현상이 발생합니다.

```yml
project:
    name: quick-start
    version: 0.0.1
    author: User
workspace:
    base: pytorch/pytorch:1.5-cuda10.1-cudnn7-runtime
    prescripts: ["pip install hyppo==0.0.1 --extra-index-url http://172.19.153.144:8081/repository/AISystem-PyPi/simple --trusted-host 172.19.153.144"]
    env:
        PYTHONUNBUFFERED: 1
    ignore:
        - .logs/
        - FashionMNIST/
services:
    hpo:
        command: python entry.py
```
