### ISSUE TITLE
train/deploy 통합

### ISSUE THREAD

**Issue by kkkdeon** [onetop21/MLAppDeploy#290]
- train/deployment project kind 제거 → component/deployment
- job/service app kind로만 구분
- train/deploy command 삭제 -> mlad up / down / update / scale(service만 가능)
- ingress를 service app 옵션으로 변경
```yaml
app:
  server:
    kind: service
    expose:
    - port: 1111
      ingress:
        rewritePath: true
        path: /server
   - port: 2222 # service만
# ingress obj 이름은 generate
```
