### ISSUE TITLE
ingress 옵션을 service app 옵션으로 변경

### ISSUE THREAD

**Issue by kkkdeon** [onetop21/MLAppDeploy#293]
Epic #290
```yaml
app:
  server:
    kind: service
    expose: #optional
    - port: 1111
      ingress:
        rewritePath: true
        path: /server
   - port: 2222 # service만
# ingress obj 이름은 generate
```
