### ISSUE TITLE
container 내 dataloader 사용시 out of shared memory 이슈

### ISSUE THREAD

**Issue by kkkdeon** [onetop21/MLAppDeploy#439]
container상에서 pytorch를 사용할 때 (정확히는 dataloader) 다음과 같은 에러가 발생
```
RuntimeError: DataLoader worker (pid 65) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. 
Please try to raise your shared memory limit.
```
container에 할당된 default 사이즈의 공유메모리 공간을 dataloader가 사용시 공간부족으로 발생
(관련 이슈: https://github.com/ultralytics/yolov3/issues/283)

**k8s 솔루션**
1. host의 shm을 empty dir로 mount하여 해결하는 방법 (sizeLimit 으로 사이즈 조정)
```
    volumeMounts:
    - mountPath: /dev/shm
      name: shmdir
  volumes:
  - name: shmdir
    emptyDir:
      medium: Memory
      sizeLimit: "256M"
```
2. hostIPC 옵션 사용(host의 공유메모리 전체 공유)
- Pod Spec hostIPC (bool)
