### ISSUE TITLE
Sudal example에서 autoscaler 옵션을 적용했을 때 오류가 발생함

### ISSUE THREAD

**Issue by JunhoeKim** [onetop21/MLAppDeploy#78]
Related to #64 

`quick_start` 예제에서 아래와 같이 app spec을 맞췄을 때 정상 실행이 안되는 모습을 발견했습니다.

```yaml
app:
  inference:
    command: python entry_worker.py
    ports: [8443]
    kind: Service
    runSpec:
      autoscaler:
        enable: true
        min: 1
        max: 4
```
